### ISSUE TITLE
[WIN] Opens in a black screen if steam isn't located in C:\

### ISSUE THREAD

**Issue by TimGoll** [WilliamVenner/gmpublisher#21]
OS: Win10
GMP-Version: beta2.2.0
WebView installed: yes

I just tried to use this awesome new tool but it seems to be not usable if steam isn't installed in the default path. It looks like this:

![image](https://user-images.githubusercontent.com/13639408/116556280-9c746c80-a8fd-11eb-8578-e20da9ea9bbe.png)

The console looks like this:

![image](https://user-images.githubusercontent.com/13639408/116556494-c7f75700-a8fd-11eb-84fd-35f59f940a97.png)

Is there any way to configure the path to the steam folder? I even tried to create a symbolic link of the steam folder to the default C directory. But it doesn't change anything

**Comment by MatStef132** [comment]
It happens to me too, my steam is installed in drive D and gmpublisher is always black.

**Comment by Pdzly** [comment]
Same but i installed gmpublish on C and Steam is on C too! but gmod itself isnt there

**Comment by Pdzly** [comment]
I have the same issue but its all on C:

**Comment by WilliamVenner** [comment]
> It happens to me too, my steam is installed in drive D and gmpublisher is always black.

Do you mean black or grey?

**Comment by WilliamVenner** [comment]
This is what's supposed to happen afterwards.

```
gmpublisher v2.2.0
Initializing Steamworks...
Initializing AppData...
WebSocket: Waiting for client on 127.0.0.1:53400
Initializing Settings...
Initializing Transactions...
Starting GUI...
Initializing Game Addons...
Locating Garry's Mod...
Steam is not connected, parsing Steam library folders...
Located!
Locating Garry's Mod...
Steam is not connected, parsing Steam library folders...
Located!
Setting breakpad minidump AppID = 4000
SteamInternal_SetMinidumpSteamID:  Caching Steam ID:  76561198040894045 [API loaded no]
[Steam] Client initialized
Locating Garry's Mod...
Getting Garry's Mod location from Steamworks...
Located!
Discovered 1700 addons
```

**Comment by WilliamVenner** [comment]
I have a strong suspicion it is actually your antivirus that is causing this problem.

**Comment by Maurice9649** [comment]
I don't know if this is actually related to this issue or not, but the newer versions also just show grey/black screen, Beta 2.0.3 works for me, but Beta 2.1+ do not, maybe try to see if the older version also work for you (Hopefully this is helpful to some degree).

**Comment by MatStef132** [comment]
> > It happens to me too, my steam is installed in drive D and gmpublisher is always black.
> 
> @MatStef132 Do you mean black or grey?

Grey

**Comment by MatStef132** [comment]
> I have a strong suspicion it is actually your antivirus that is causing this problem.

I'm using windows defender

**Comment by WilliamVenner** [comment]
> I don't know if this is actually related to this issue or not, but the newer versions also just show grey/black screen, Beta 2.0.3 works for me, but Beta 2.1+ do not, maybe try to see if the older version also work for you (Hopefully this is helpful to some degree).

@Maurice9649 Which version specifically does it break on?

**Comment by Maurice9649** [comment]
> 
> 
> > I don't know if this is actually related to this issue or not, but the newer versions also just show grey/black screen, Beta 2.0.3 works for me, but Beta 2.1+ do not, maybe try to see if the older version also work for you (Hopefully this is helpful to some degree).
> 
> @Maurice9649 Which version specifically does it break on?

Since Version 2.1.0 [Tested every version from the newest to 2.0.3 where it started working]. Using the binaries from the Releases.

**Comment by WilliamVenner** [comment]
[gmpublisher_2.2.0_win64.zip](https://github.com/WilliamVenner/gmpublisher/files/6411676/gmpublisher_2.2.0_win64.zip)

Please give this build a go, I think it should fix the problem.

@Maurice9649 @MatStef132 @Pdzly @TimGoll

**Comment by TimGoll** [comment]
ohhh, so first I just noticed that my error was because I hadn't steam running. I tried your new version (with steam running), it is still not working:

![image](https://user-images.githubusercontent.com/13639408/116818462-cc28ac00-ab6b-11eb-9e07-01ab75aafebc.png)

**Comment by WilliamVenner** [comment]
[gmpublisher_2.2.1_win64.zip](https://github.com/WilliamVenner/gmpublisher/files/6411898/gmpublisher_2.2.1_win64.zip)

Weird, looks like I fixed one problem and you've encountered a completely different one.

I've added some extra logging into this build, hopefully the JavaScript error that I believe is happening will show up in your git bash.

**Comment by TimGoll** [comment]
[output.zip](https://github.com/WilliamVenner/gmpublisher/files/6411920/output.zip)

Now there is an error in the `output.err` file:

```txt
=== JavaScript Error! ===
[svelte-i18n] Cannot format a message without first setting the initial locale.
Error: [svelte-i18n] Cannot format a message without first setting the initial locale.
    at Array.Zt (file://custom-protocol-taurilocalhost/build/bundle.js:1:55927)
    at iy (file://custom-protocol-taurilocalhost/build/bundle.js:1:370210)
    at r (file://custom-protocol-taurilocalhost/build/bundle.js:1:3643)
    at ie (file://custom-protocol-taurilocalhost/build/bundle.js:1:4097)
    at ay (file://custom-protocol-taurilocalhost/build/bundle.js:1:371614)
    at fe (file://custom-protocol-taurilocalhost/build/bundle.js:1:5565)
    at new cy (file://custom-protocol-taurilocalhost/build/bundle.js:1:372941)
    at lE (file://custom-protocol-taurilocalhost/build/bundle.js:1:432836)
    at fe (file://custom-protocol-taurilocalhost/build/bundle.js:1:5565)
    at new uE.target (file://custom-protocol-taurilocalhost/build/bundle.js:1:434964)
```

**Comment by WilliamVenner** [comment]
What is `language` set to in `%appdata/gmpublisher/settings.json`?

**Comment by TimGoll** [comment]
![image](https://user-images.githubusercontent.com/13639408/116821798-9a1f4600-ab7b-11eb-8e21-26458a23d617.png)
this file does not exist

**Comment by WilliamVenner** [comment]
[gmpublisher_2.2.1_win64.zip](https://github.com/WilliamVenner/gmpublisher/files/6412043/gmpublisher_2.2.1_win64.zip)

Give this one a try. If it doesn't work, please add me on Discord: Billy#0420

**Comment by TimGoll** [comment]
[output.zip](https://github.com/WilliamVenner/gmpublisher/files/6412048/output.zip)

It works, you're a genious! I added the log nonetheless, maybe you need it for something. There is still no `settings.json` though.

**Comment by WilliamVenner** [comment]
Awesome, thank you for your help.

If you resize the window, does `settings.json` appear?

**Comment by TimGoll** [comment]
yes, it appears

**Comment by Mesea232** [comment]
The same thing is happening to me but instead of being black is white, someone helps me
